### ISSUE TITLE
List/Menu?

### ISSUE THREAD

**Issue by 2br-2b** [nturpin0/OutputKit#1]
Hello!

I love your shortcut, and I use it all the time for personal projects.  I am hoping to release some soon.

I had one question.  How do you get the result of a menu when an option is chosen?  Does the window automatically close when an option is chosen?

Thank you!
2br-2b

**Comment by nturpin0** [comment]
When using the ml mlsub mlnote ml image /ml tags ?

Sorry, I realise this isn't documented at all, some of the links here go into more details how the vcf/vcard in lists work in general but not specifically with OutputKit

https://nturpin0.github.io/appsupport/MenuBuilder/about.html 
https://www.reddit.com/r/shortcuts/comments/aibvkg/creating_visually_appealing_menus/

Title of the chosen item as set under <ml> should automatically flow to the next action from Choose from List. You can retrieve the Subtitle if you use Get Variable, select Magic Variable point to the Choose From List, then select variable, change the type to contact the company, or Notes if you are also using the <mlnote> tag from the more recent update. Notes is there for passing hidden information on a selection.
